<html>
<head>
    <style type="text/css">@media screen and (max-width: 480px) {
            .background_inner {
                padding: 0 !important;
                background: #fff !important
            }

            .container {
                padding: 0 8px 16px !important
            }

            .footer_container {
                border-top: 1px solid #e2e2e2 !important
            }

            .AnnualThankYouEmail .background_inner {
                padding: 10px 0 !important
            }

            .polish_background_inner {
                padding: 10px 0 !important
            }

            .polish_header_logo img.header_logo_img {
                width: 118px !important;
                height: 40px !important
            }

            .polish_header_title {
                font-size: 16px !important;
                padding-top: 0 !important;
                padding-bottom: 5px !important
            }

            .polish_question_text {
                line-height: 1.3 !important
            }

            .polish_story .voters_list, .polish_story .user_link {
                line-height: 1.5 !important
            }

            .polish_story .truncated_q_text, .polish_story .qtext_para {
                line-height: 1.5 !important
            }

            .polish_story .content_header {
                padding: 6px 0 !important
            }

            .EndOfYearLookbackEmail .stat_large {
                font-size: 28px !important
            }

            .EndOfYearLookbackEmail .content_text {
                text-align: center !important
            }

            .EndOfYearLookbackEmail .half_column {
                width: 100% !important
            }

            .EndOfYearLookbackEmail .img_wrapper {
                margin: 10px auto !important
            }

            .TopicDigestEmail .topic_digest_header_logo img.polish_header_logo_img {
                width: 89px !important;
                height: 30px !important
            }

            .TopicDigestEmail .topic_digest_header_title {
                font-size: 16px !important;
                padding-top: 0 !important;
                padding-bottom: 5px !important
            }

            .WriteDigestEmail .question_text .rendered_qtext {
                font-size: 16px !important
            }

            .email_app_link-content {
                display: block !important;
                text-align: center !important
            }

            .email_app_link-text, .email_app_link-badges_wrapper {
                display: block !important
            }

            .email_app_link-text {
                padding-bottom: 0 !important;
                box-sizing: border-box !important
            }

            .email_app_link-badges_wrapper {
                padding-left: 10px !important
            }
        }

        @media screen and (max-width: 600px) {
            .DigestEmail .mobile_image.digest_ad {
                display: table !important;
                width: 92vw
            }

            .DigestEmail .desktop_image.digest_ad {
                display: none !important
            }
        }</style>
    <title>New Questions Were Asked</title>
</head>
<body class="email_body">
<div class="q_ltr u-ltr lang_en" dir="ltr" lang="en">
    <table class="Email SearchEngagementEmail EmailComponent background" cellpadding="0" border="0"
           style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; background: #eee; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 13px; width: 100%; height: 100%; text-align: left;"
           width="100%" height="100%" align="left">
        <tbody>
        <tr>
            <td class="polish_background_inner" align="center" valign="top"
                style="border-collapse: collapse; padding: 0; background: #fff;">
                <table cellpadding="0" cellspacing="0" border="0"
                       style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;">
                    <tbody>
                    <tr>
                        <td class="container" align="left"
                            style="border-collapse: collapse; background: #fff; padding: 32px; width: 525px; height: 100%; border-radius: 3px;"
                            width="525" height="100%">
                            <table class="polish_container_inner"
                                   style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%; cellpadding: 0; cellspacing: 0; border: 0;"
                                   width="100%">
                                <tbody>
                                <tr>
                                    <td class="polish_header" style="border-collapse: collapse;">
                                        <table cellpadding="0" cellspacing="0" border="0" width="100%"
                                               style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;">
                                            <tbody>
                                            <tr>
                                                <div class="fixed_header">
                                                    <div class="header_main" style="position: relative;
        background: rgba(20, 75, 97, .64);
        min-height: 44px;
        width: 100%;
        display: flex;
        align-items: center;">
                                                        <a href="${host}?utm_medium=email&utm_source=new.questions&utm_term=header"
                                                           style="display: flex; padding: 0px 10px; text-decoration: none;">
                                                            <div style="align-self: center; font-size: 30px; font-weight: bold; color: #fff; ">
                                                                ibeere
                                                            </div>
                                                        </a>
                                                    </div>
                                                    <div class="mweb_new_stories_button_wrapper"
                                                         id="mweb_new_stories_button_wrapper"></div>
                                                </div>
                                            </tr>                                            <tr>
                                                <td class="polish_header_title"
                                                    style="border-collapse: collapse; text-align: center; font-size: 19px; font-family: Georgia,Times,'Times New Roman','Hiragino Kaku Gothic Pro','Meiryo',serif; color: #333; font-weight: 400; padding-top: 20px;"
                                                    align="center">New Questions Were Asked
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-collapse: collapse;">
                                                    <table class="polish_header_wrapper"
                                                           style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; cellpadding: 0; border: 0; width: 100%;"
                                                           width="100%">
                                                        <tbody>
                                                        <tr>
                                                            <td style="border-collapse: collapse;"></td>
                                                            <td class="polish_header_line"
                                                                style="border-collapse: collapse; border-bottom: 1px solid rgba(20, 75, 97, .64); height: 1px; width: 198px;"
                                                                width="198" height="1"></td>
                                                            <td style="border-collapse: collapse;"></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr class="body_container" id="simple-content-row">
                                    <td class="body_content" bgcolor="#ffffff" style="border-collapse: collapse;">
                                        <table style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%;"
                                               cellpadding="0" cellspacing="0" border="0" width="100%">
                                            <tbody>
                                            <tr>
                                                <td style="border-collapse: collapse;">
                                                    <table style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%;"
                                                           cellpadding="0" cellspacing="0" border="0" width="100%">
                                                        <tbody>
                                                        <tr>
                                                            <td style="border-collapse: collapse;">
                                                                <div class="no_para_breaks">
                                                                    <div data-clog-trigger="impression"
                                                                         data-clog-metadata="{&quot;action_log_target&quot;: {&quot;type&quot;: 33, &quot;hash&quot;: &quot;0|4|1|100952211&quot;}}"
                                                                         data-clog-event-type="ActionLogImpression"
                                                                         id="__w2_wnEkvYB325_actionable">
                                                                        <table class="polish_separator_wrapper"
                                                                               style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; cellpadding: 0; border: 0; width: 100%;"
                                                                               width="100%">
                                                                            <tbody>
                                                                            <tr>
                                                                                <td style="border-collapse: collapse;"></td>
                                                                                <td style="border-collapse: collapse;"></td>
                                                                            </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <table class="story_wrapper" cellspacing="0"
                                                                               border="0"
                                                                               style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%;"
                                                                               width="100%">
                                                                            <tbody>
                                                                            <tr>
                                                                                <td class="story"
                                                                                    style="border-collapse: collapse; padding: 20px 0; border-bottom: 0;">
                                                                                    <table class="digest_story_wrapper"
                                                                                           cellpadding="0"
                                                                                           cellspacing="0" border="0"
                                                                                           style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; width: 100%;"
                                                                                           width="100%">
                                                                                        <tbody>
                                                                                        <tr>
                                                                                            <td class="reason"
                                                                                                style="border-collapse: collapse; padding-bottom: 4px;">
                                                                                                <table class="digest_reason"
                                                                                                       cellpadding="0"
                                                                                                       cellspacing="0"
                                                                                                       border="0"
                                                                                                       style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0;">
                                                                                                    <tbody>
                                                                                                    <tr>
                                                                                                        <td valign="top"
                                                                                                            style="border-collapse: collapse;"></td>
                                                                                                        <td class="reason_text"
                                                                                                            style="border-collapse: collapse; font-size: 11px; color: #999; letter-spacing: .2px;"></td>
                                                                                                    </tr>
                                                                                                    </tbody>
                                                                                                </table>
                                                                                            </td>
                                                                                        </tr>
                                                                                        <tr>
                                                                                            <td style="border-collapse: collapse;"></td>
                                                                                        </tr>
                                                                                        <#list questions as question>
                                                                                        <tr>
                                                                                            <td style="border-collapse: collapse;">
                                                                                                <a class="question_text"
                                                                                                   href="${question.url}?utm_medium=email&utm_source=new.questions&utm_term=question"
                                                                                                   style="margin-top: 15px; margin-bottom:15px; text-align: center; text-decoration: none; display: block; font-size: 19px; letter-spacing: -0.5px; font-weight: bold; color: #333; line-height: 1.4;"><span class="rendered_qtext" style="word-break: break-word;">${question.text}</span></a>
                                                                                            </td>
                                                                                        </tr>
                                                                                        </#list>
                                                                                        </tbody>
                                                                                    </table>
                                                                                </td>
                                                                            </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td class="w30" style="border-collapse: collapse;">&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="border-collapse: collapse;">
                                        <div class="polish_button_wrapper"
                                             style="text-align: center; margin-bottom: 25px;"><a
                                                    class="polish_action_button"
                                                    href="${host}?utm_medium=email&utm_source=new.questions&utm_term=search-more"
                                                    style="font-size: 15px; line-height: 1.4; border-radius: 3px; box-shadow: 0 1px 1px 0 rgba(200,200,200,0.2); display: inline-block; outline: 0; padding: 15px 20px; text-align: center; text-decoration: none; cursor: pointer; background-color: #168de9; color: #fff; padding: 15px 25px;">Search More on ibeere</a></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="border-collapse: collapse;"></td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<style type="text/css">
    @media (max-width: 812px) {
        .ad_email_background .ad_table {
            margin: 0;
        }
    }

    @media (max-width: 812px) {
        .ad_email_background .ad_table {
            margin: 0;
        }
    }
</style>
</body>
</html>